version: "3"

services:
  test-new-structure-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
  test-new-structure-ui:
    build:
      context: apps/ui
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - test-new-structure-api
    links:
      - test-new-structure-api
